version: '3'

services:
  streamlit:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app/src
      - ./.streamlit:/.streamlit
    ports:
      - '8501:8501'
    command: streamlit run /app/src/app.py